SELECT A.TABLE_NAME,
       A.COLUMN_NAME,
       A.OWNER AS SCHEMA

    FROM CDB_CONS_COLUMNS A

    JOIN CDB_CONSTRAINTS C
        ON A.OWNER = C.OWNER
           AND A.CONSTRAINT_NAME = C.CONSTRAINT_NAME

    JOIN CDB_OBJECTS O
        ON A.TABLE_NAME = O.OBJECT_NAME
           AND C.OWNER = O.OWNER

    WHERE C.CONSTRAINT_TYPE = 'P'
        AND OBJECT_TYPE IN ('TABLE', 'MATERIALIZED VIEW')
        AND A.OWNER IN ('PUB_DS','MBR','MFR_STG','MBR_DEV','REP_B2B')
        AND A.TABLE_NAME not like '%TMP\_%' escape '\'
        AND A.TABLE_NAME not like '%_OLD'

    ORDER BY C.OWNER,
             A.TABLE_NAME
